export default async function handler(req, res) {
  const auth = req.headers.authorization;

  // Check authorization
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  // Your task logic
  console.log("Running hourly task:", new Date().toISOString());
  res.status(200).json({ ok: true });
}
