name: Every Minute Trigger

on:
  schedule:
    - cron: "* * * * *"  # every minute
  workflow_dispatch:      # allow manual trigger

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API
        run: |
          curl -X POST https://solana-clicker-six.vercel.app/api/run-task \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
